install! 'cocoapods', deterministic_uuids: false, share_schemes_for_development_pods: false

# Supported platform.
platform :ios, '9.0'

# Use frameworks for Swift.
use_frameworks!

# Ignore the pod warnings.
inhibit_all_warnings!

target 'Application' do
  pod 'Stella', :path => '../'

  target 'Tests' do
    inherit! :search_paths

    # Frameworks needed for testing.
    pod 'Keychain', '~> 0.3'

    # The test frameworks
    pod 'Quick',  '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited) YES'
    end
  end
end
