install! 'cocoapods', deterministic_uuids: false,
                      share_schemes_for_development_pods: false

platform :ios, '9.0'

target 'Stella Example' do
  use_frameworks!

  pod 'Stella', :path => '../'

  target 'Stella_Tests' do
    inherit! :search_paths
    
    # Frameworks needed for testing.
    pod 'Keychain', '~> 0.3'

    # The test frameworks
    pod 'Quick',  '~> 0.10'
    pod 'Nimble', '~> 5.0'
  end
end

post_install do |installer|
  # Make sure all targets have the right swift version set
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited) YES'
    end
  end
end
