use_frameworks!

target 'Stella_Tests' do
  pod 'Stella', :path => '../'

  # The test frameworks
  pod 'Quick',  '~> 0.10'
  pod 'Nimble', '~> 5.0'
end

post_install do |installer|
  # Make sure all targets have the right swift version set
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited) YES'
    end
  end
end
